# Generated by Django 2.1.7 on 2019-08-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mobilenum', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fileurl', models.CharField(max_length=255)),
            ],
        ),
    ]
